export const SHIELDED_POOL_V5_ABI = [
  {
    type: "function",
    name: "transact",
    inputs: [
      { name: "proof_with_hints", type: "core::array::Span::<core::felt252>" },
      { name: "recipient", type: "core::starknet::contract_address::ContractAddress" },
      { name: "relayer", type: "core::starknet::contract_address::ContractAddress" },
      { name: "fee", type: "core::integer::u256" },
      { name: "ext_amount", type: "core::integer::u256" },
      { name: "ext_data_hash", type: "core::integer::u256" },
      { name: "encrypted_output_0", type: "core::array::Span::<core::felt252>" },
      { name: "encrypted_output_1", type: "core::array::Span::<core::felt252>" },
      { name: "ephemeral_pubkey_0", type: "core::integer::u256" },
      { name: "ephemeral_pubkey_1", type: "core::integer::u256" },
    ],
    outputs: [],
    state_mutability: "external",
  },
  {
    type: "function",
    name: "get_last_root",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "get_next_index",
    inputs: [],
    outputs: [{ type: "core::integer::u32" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_spent",
    inputs: [{ name: "nullifier_hash", type: "core::integer::u256" }],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "total_vault_shares",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "total_pool_assets",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "asp_root",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "is_asp_enabled",
    inputs: [],
    outputs: [{ type: "core::bool" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "max_deposit_amount",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
  {
    type: "function",
    name: "min_deposit_amount",
    inputs: [],
    outputs: [{ type: "core::integer::u256" }],
    state_mutability: "view",
  },
] as const;
